- hosts: localhost
  tasks:
        - package:
               name: "httpd"
               state: present
        - copy:
               src: "/root/index.html"
               dest: "/var/www/html"
        - service:
               name: "httpd"
               state: restarted
               enabled: yes
        - firewalld:
               state: enabled
               port: "80/tcp"
               immediate: yes
               permanent: yes
