- hosts: localhost
  gather_facts: no
  tasks:

  - name: config hdfs file
    blockinfile:
        path: "/etc/hadoop/hdfs-site.xml"
        state: present
        insertafter: "<configuration>"
        block: |
          <property>
          <name>dfs.data.dir</name>
          <value>/data</value>
          </property>

  - name: config core file
    blockinfile:
        path: "/etc/hadoop/core-site.xml"
        state: present
        insertafter: "<configuration>"
        block: |
          <property>
          <name>fs.default.name</name>
          <value>hdfs://master.lw.com:9001</value>
          </property>
  - name: start data node
    command: "hadoop-daemon.sh start datanode"
  - name: "Flushing firewall"
    command: "iptables -F"
    
