- hosts: localhost
  tasks:
       - pip:
           name: docker-py
           state: present
       - docker_container:
            name: nikuu
            image: centos
            state: started
            interactive: yes
            tty: yes
            
   
