- hosts: 192.168.43.68
  tasks:

  - name: Copy java rpm package 
    copy:
     src: /root/Desktop/SOFTWARES/jdk-8u171-linux-x64.rpm
     dest: /root/Desktop/jdk-8u171-linux-x64.rpm

  - name: Install java package
    yum:
     name: /root/Desktop/jdk-8u171-linux-x64.rpm
     state: present

  - name: Set path for JAVA_HOME
    blockinfile:
     path: /root/.bashrc
     state: present
     insertafter: "fi"
     block: |
       'export JAVA_HOME=/usr/java/jdk1.8.0_171-amd64/'
       'export PATH=/usr/java/jdk1.8.0_171-amd64/bin:/usr/java/jdk1.8.0_171-amd64/bin:$PATH'

  - name: Copy hadoop rpm package   
    copy:
     src: /root/Desktop/SOFTWARES/hadoop-1.2.1-1.x86_64.rpm
     dest: /root/Desktop/hadoop-1.2.1-1.x86_64.rpm

  - name: Install hadoop package
    command: rpm -ivh /root/Desktop/hadoop-1.2.1-1.x86_64.rpm 
